CREATE DATABASE SCHOOLGHI;
USE SCHOOLGHI ;


CREATE TABLE FACULTY (
ID INT PRIMARY KEY NOT NULL auto_increment, 
NAME  NVARCHAR(255),
EMAIL NVARCHAR(255),
SALARY INT
);

INSERT INTO FACULTY VALUES(NULL,"Ali " , "a@gmail.com",'50000' );
INSERT INTO FACULTY VALUES(NULL,"Hasan" , "b@gmail.com",'50000' );
INSERT INTO FACULTY VALUES(NULL,"Husain" , "c@gmail.com",'50000');
INSERT INTO FACULTY VALUES(NULL,"Hassan" ,"d@gmail.com",'50000');
INSERT INTO FACULTY VALUES(NULL,"Arsalan" , "e@gmail.com",'50000');

SELECT * FROM  FACULTY;


 CREATE TABLE STUDENT (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    STUDENTNAME NVARCHAR(255),
    COURES NVARCHAR(255),
    FACULTYNAME VARCHAR(55),    
    FOREIGN KEY (FACULTYNAME) REFERENCES FACULTY (id)
);
 



INSERT INTO STUDENT  VALUES(NULL,"AFFAN" , "OFFICE", "1");
INSERT INTO STUDENT  VALUES(NULL,"ANAS" , "CPISM", "2");
INSERT INTO STUDENT  VALUES(NULL,"AHMED" , "SQL", "3");
INSERT INTO STUDENT  VALUES(NULL,"HARRYSON" , "APPDEVELOPMENT", "5");
INSERT INTO STUDENT  VALUES(NULL,"LAIBA" , "MACHINE LEARNING", "5");
INSERT INTO STUDENT  VALUES(NULL,"MISBAH" , "DATA SCIENCE", "5");
INSERT INTO STUDENT  VALUES(NULL,"OSMANA" , "PHP", "2");
INSERT INTO STUDENT  VALUES(NULL,"HAMZA" , "PYTHON", "5");
INSERT INTO STUDENT  VALUES(NULL,"ZAID" , "ARTIFICIAL INTELLIGENCE", "5");
INSERT INTO STUDENT  VALUES(NULL,"HAROON" , "ETHICAL HACKING", NULL);






SELECT 
    STUDENTNAME, COURES, NAME
FROM
    FACULTY
        INNER JOIN
    STUDENT ON FACULTY.ID = STUDENT.FACULTYNAME;
    
    
    SELECT 
    STUDENTNAME, COURES, NAME
FROM
    FACULTY
        RIGHT JOIN
    STUDENT ON FACULTY.ID = STUDENT.FACULTYNAME;
    
    
    SELECT 
    STUDENTNAME, COURES, NAME
FROM
    FACULTY
        LEFT JOIN
    STUDENT ON FACULTY.ID = STUDENT.FACULTYNAME;
    
    


    SELECT 
    STUDENTNAME, COURES, NAME
FROM
    FACULTY
        RIGHT JOIN
    STUDENT ON FACULTY.ID = STUDENT.FACULTYNAME
    
    UNION 
    SELECT 
    STUDENTNAME, COURES, NAME
FROM
    FACULTY
        LEFT JOIN
    STUDENT ON FACULTY.ID = STUDENT.FACULTYNAME;
    
    